- Dockerfile
- config/rbac/role.yaml
- controllers/repository_controller.go
fix: failed to build the image
> fix: failed to build the image

- .github/workflows/codecov.yaml
- Makefile
- README.md
- codecov.yaml
> feat: add codecov

- controllers/repository_controller.go
- pkg/repository/chartmuseum.go
Fix: https://github.com/kubebb/core/issues/28
> fix: unexpected repository reconcile logic

- pkg/repository/chartmuseum.go
> fix: secret name error

- pkg/helm/cmd.go
- pkg/helm/helm.go
- pkg/repository/chartmuseum.go
fix: do 'add, update, remove' repo
Fix: https://github.com/kubebb/core/issues/42
> fix: do 'add, update, remove' repo

- controllers/component_controller.go
> chore: optimize code

- .github/workflows/image_build.yml
- Makefile
- tests/kind-config-3nodes.yaml
Changelogs:
1. Add a new config file to create a 3-nodes kind cluster
2. Add a new github aciton to build-and-push docker image
> add 3nodes kind cluster and enable build-and-push action

- controllers/repository_controller.go
- pkg/repository/chartmuseum.go
cleanup: remove redundant parameters and variables
> cleanup: remove redundant parameters and variables

- .github/workflows/image_build.yml
> fix image build failures

- codecov.yaml
> chore: disable codecov patch

- main.go
fix: fix livenessProbe and readinessProbe do not work properly
> fix: fix livenessProbe and readinessProbe do not work properly

- .github/workflows/example_test.yaml
- Makefile
- config/samples/core_v1alpha1_grafana_subscription.yaml
- config/samples/core_v1alpha1_nginx_componentplan.yaml
- config/samples/example-test.sh
Fix: https://github.com/kubebb/core/issues/35
> feat: add example test

- .github/workflows/gpt-review.yaml
Add https://github.com/anc95/ChatGPT-CodeReview to project:
1. This project has 2.6K stars. 
2. This action needs `secrets.OPENAI_API_KEY` to work. **(need add this secrets)**
3. This action will work when the PR is labeled `gpt review` to save money. **(need add this lable)**
4. This action will not work when the PR is too big to save money.
5. Some Code review example in go can see: https://github.com/pokt-network/pocket/pull/763#discussion_r1202271619 https://github.com/pokt-network/pocket/pull/763#discussion_r1206631892 https://github.com/pokt-network/pocket/pull/727#discussion_r1192715044
> feat: add gpt review

- pkg/repository/chartmuseum.go
fix: sync component status at the first time
Fix: https://github.com/kubebb/core/issues/77
```shell
root@macbookpro:~/workspace/core/config/samples# kubectl apply -f core_v1alpha1_repository_bitnami.yaml
repository.core.kubebb.k8s.com.cn/kubebb-sample created
root@macbookpro:~/workspace/core/config/samples# kubectl get components.core.kubebb.k8s.com.cn -nkubebb-system -oyaml -w
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Component
metadata:
creationTimestamp: "2023-07-04T07:53:10Z"
generation: 1
labels:
kubebb.component.repository: kubebb-sample
name: kubebb-sample.minio
namespace: kubebb-system
ownerReferences:
- apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Repository
name: kubebb-sample
uid: de180e71-6df6-42fc-937d-15a8cbd81159
resourceVersion: "46071"
uid: …
```
> fix: sync component status at the first time

- controllers/componentplan_controller.go
- pkg/helm/cmd.go
- pkg/helm/cmd_test.go
- pkg/utils/resource.go
Follow #75 
Fix kubebb/components#28
> fix: add log, retry time update, only update namespaced resource name

- pkg/helm/repo.go
- pkg/repository/chartmuseum.go
fix: set default timeout in repository
Fix: https://github.com/kubebb/core/issues/95
> fix: set default timeout in repository

- pkg/repository/chartmuseum.go
feat: change method of reading files
Fix: #89
> feat: change method of reading files

- Dockerfile
- goreleaser.dockefile
> chore: remove helm binary in dockerfile

- api/v1alpha1/repository.go
- api/v1alpha1/repository_types.go
- config/crd/bases/core.kubebb.k8s.com.cn_repositories.yaml
- controllers/repository_controller.go
fix: define repository types
Maybe Fix: https://github.com/kubebb/core/issues/103
> fix: define repository types

- api/v1alpha1/componentplan.go
- config/samples/core_v1alpha1_nginx_componentplan_long_ready.yaml
- config/samples/example-test.sh
- controllers/componentplan_controller.go
- pkg/helm/post_renderer_test.go
Fix #85 
the second commit xref #105
Fix #117
> feat: add more condition and make cpl concurrent install

- controllers/componentplan_controller.go
- pkg/helm/cmd.go
> chore: add more log about helm release

- controllers/component_controller.go
fix: remove unnecessary variables
Fix: #122
> fix: remove unnecessary variables

- api/v1alpha1/subscription.go
- controllers/subscription_controller.go
- main.go
feat: subscription controller add event logic
> feat: subscription controller add event logic

- api/v1alpha1/component.go
- api/v1alpha1/subscription.go
- controllers/component_controller.go
- controllers/subscription_controller.go
fix: incorrect event type
https://book.kubebuilder.io/reference/raising-events.html#writing-events
> fix: incorrect event type

- controllers/componentplan_controller.go
> refactor: simplify the code

- controllers/componentplan_controller.go
> perf: optimize logic

- controllers/componentplan_controller.go
- main.go
feat: componentplan controller add event logic
Fix: https://github.com/kubebb/core/issues/64
> feat: componentplan controller add event logic

- controllers/componentplan_controller.go
> fix: retry time cant show

- pkg/helm/helm.go
- pkg/utils/resource.go
> fix: generated resource cant worr with no crd installed

- controllers/componentplan_controller.go
- pkg/utils/resource.go
same logic with #78 
side work for #137
> fix: non-standard helm chart may lack ns

- controllers/componentplan_controller.go
> fix: post-hook install failed

- controllers/component_controller.go
- controllers/componentplan_controller.go
- controllers/repository_controller.go
- controllers/subscription_controller.go
- pkg/helm/helm.go
> fix: use right debug log level

- controllers/repository_controller.go
- main.go
feat: add some events to the repository controller
Fix: https://github.com/kubebb/core/issues/143
> feat: add some events to the repository controller

- api/v1alpha1/common.go
- api/v1alpha1/common_test.go
> fix: empty version list should return false on keep

- api/v1alpha1/repository_types.go
- config/crd/bases/core.kubebb.k8s.com.cn_repositories.yaml
- pkg/repository/chartmuseum.go
feat: keyword array length limit
> feat: keyword array length limit

- pipeline/rating/README.md
- pipeline/rating/pipeline.yaml
- pipeline/rating/rbac/pipelinerun-clusterrole.yaml
- pipeline/rating/rbac/pipelinerun-rolebinding.yaml
- pipeline/rating/rbac/pipelinerun-serviceaccount.yaml
- pipeline/rating/rbac/task-clusterrole.yaml
- pipeline/rating/rbac/task-rolebinding.yaml
- pipeline/rating/rbac/task-serviceaccount.yaml
- pipeline/rating/samples/pipeline-run.yaml
- pipeline/rating/tasks/task-helm-lint.yaml
- pipeline/rating/tasks/task-rbac.yaml
feat: develop a pipeline for rating
> feat: develop a pipeline for rating

- .github/update-helm-chart-version.sh
> feat: sync pipeline resources

- pkg/helm/repo.go
> fix: format log message in repo

- api/v1alpha1/repository_test.go
- config/samples/example-test.sh
- controllers/repository_controller.go
- pkg/helm/cmd.go
- pkg/helm/helm.go
- pkg/repository/chartmuseum.go
Partially For kubebb/core#194
Added test cases for Repository.NamespacedName()
Also added comments and corrected typos
> for: add test cases and comments

- api/v1alpha1/common_test.go
/kind test
add test cases for `ValuesReference`
For: https://github.com/kubebb/core/issues/194
> chore: add test cases for ValuesReference

- api/v1alpha1/common_test.go
/kind test
chore: add test cases for Config
For #194
> chore: add test cases for Config

- pkg/helm/repo.go
- pkg/repository/chartmuseum.go
feat: add auth args when helm repo add/update
Fix: #113
> feat: add auth args when helm repo add/update

- api/v1alpha1/repository_test.go
> chore: add test cases for repository.go

- pkg/repoimage/filter_test.go
- pkg/repoimage/updater.go
> fix: support ImageOverride.NewPath is empty

- README.md
- README_zh.md
> docs: update roadmap link

- api/v1alpha1/common_test.go
- api/v1alpha1/condition.go
- api/v1alpha1/condition_test.go
- api/v1alpha1/repository_test.go
> chore: add test cases for condition.go

- api/v1alpha1/subscription_test.go
/kind test
add test cases for subscrption.
For #194
> chore: add test cases for subscription

- api/v1alpha1/common_test.go
> chore: add test cases for common.go

- main.go
/kind cleanup
1. Environment variable has the highest priority
2. options.CertDir can be configured through the config file, priority 2
3. The default directory has a value of priority 3
4. If the environment variable is configured, but there is a configuration error, exit directly.
Fixes #
> chore: add environment variable ENABLE_WEBHOOKS

- controllers/componentplan_controller.go
- controllers/repository_controller.go
- controllers/subscription_controller.go
/kind cleanup
[chore: rename maxRetryErr to errMaxRetry](https://github.com/kubebb/core/commit/d9ddfc22c6eeb0a7f467b28470ab4098ebfb38f6)
[chore: remove duplicate imported packages](https://github.com/kubebb/core/commit/5d15d079e93a44a99b0410edfb7ddad5530c7c95)
Fixes #
> Two minor cleanup

- api/v1alpha1/componentplan.go
- api/v1alpha1/componentplan_test.go
- controllers/componentplan_controller.go
> chore: add test cases for componentplan.go

- api/v1alpha1/portal_types.go
- config/crd/bases/core.kubebb.k8s.com.cn_portals.yaml
- config/webhook/manifests.yaml
> chore: mark entry and path as required fields

- pkg/helm/helm.go
feat: add auth args when helm install/upgrade
Fixes #114
> feat: add auth args when helm install/upgrade

- controllers/repository_controller.go
- pkg/repository/chartmuseum.go
- pkg/repository/iwatch.go
feat: output Event when startup fails
Fix: #205
> feat: output Event when startup fails

- api/v1alpha1/common_test.go
- api/v1alpha1/component_test.go
- api/v1alpha1/componentplan_test.go
- api/v1alpha1/condition_test.go
- api/v1alpha1/repository_test.go
- pkg/utils/path_test.go
> chore: add test cases for pkg/utils/path.go

- api/v1alpha1/componentplan_webhook.go
- api/v1alpha1/webhook.go
> fix: componentplan webhook not check spec.componentRef

- api/v1alpha1/common_test.go
/kind cleanup
We merged #245 in such a hurry that the pr actually had 3 commits when it really only needed 1. We updated the "Dismiss stale pull request approvals when new commits are pushed" configuration of the code repository to make sure this won't happen next time.
For #245
> chore: fix golangci-lint error in tests

- api/v1alpha1/repository.go
- controllers/repository_controller.go
- main.go
/kind feature
impl Rating.
Fix: https://github.com/kubebb/core/issues/250
> feat: repository controller supports sync serviceaccount

- controllers/componentplan_controller.go
- pkg/helm/helm.go
> refactor: simplify several helm func

- config/samples/core_v1alpha1_componentplan_chartmuseum.yaml
- config/samples/core_v1alpha1_componentplan_mynginx.yaml
- config/samples/core_v1alpha1_repository_chartmuseum.yaml
- config/samples/core_v1alpha1_repository_kubebb.yaml
- config/samples/example-test.sh
/kind chore
Fix: #228 
Fixes #
> chore: add test cases for repository(basic auth enabled)

- api/v1alpha1/portal_webhook.go
- config/samples/example-test.sh
- config/webhook/manifests.yaml
/kind bug
Fixes #264 
This webhook acutually has no specific functionalities yet,but it does sometime in the future.
> fix: enable defaulter and validator in portal webhook

- api/v1alpha1/portal_types.go
- config/crd/bases/core.kubebb.k8s.com.cn_portals.yaml
- config/rbac/role.yaml
- config/samples/core_v1alpha1_portal_another.yaml
- config/samples/core_v1alpha1_portal_duplicate.yaml
- config/samples/example-test.sh
- controllers/portal_controller.go
- main.go
Fixes #225 
Two new fields are added in Portal.
Duplicate         bool     `json:"duplicate"`
ConflictedPortals []string `json:"conflicted-portals"`
duplicate is true when there is at least one duplicate in the client. 
ConflictedPortals is a list of namespacedname of portals that are equivalent to the current portal. 
An example of error message: 
1.6920898037031348e+09  ERROR   found portals with duplicate path and entry     {"controller": "portal", "controllerGroup": "core.kubebb.k8s.com.cn", "controllerKind": "Portal", "portal": {"name":"portal-example-duplicate"}, "namespace": "", "name": "portal-example-duplicate", "reconcileID": "c30349bb-67c2-4234-add5-e434ce3b1bfa", "duplicates": ["/portal-example"], "error": "duplicate error"}
Two portal.yaml are also added for testing.
> feat: add portal_controller.go and two portal.yaml for testing

- api/v1alpha1/subscription.go
- api/v1alpha1/subscription_test.go
- api/v1alpha1/subscription_types.go
- api/v1alpha1/subscription_webhook.go
- api/v1alpha1/webhook.go
- config/crd/bases/core.kubebb.k8s.com.cn_subscriptions.yaml
- config/samples/core_v1alpha1_loki_subscription_schedule.yaml
- config/samples/example-test.sh
- controllers/subscription_controller.go
- go.mod
- go.sum
- main.go
> feat: add Schedule to SubscriptionSpec

- api/v1alpha1/common.go
- api/v1alpha1/componentplan.go
- config/crd/bases/core.kubebb.k8s.com.cn_componentplans.yaml
- config/crd/bases/core.kubebb.k8s.com.cn_subscriptions.yaml
- config/samples/example-test.sh
- controllers/componentplan_controller.go
- pkg/helm/cmd.go
- pkg/helm/helm.go
- pkg/helm/helm_release_workpool.go
Just need add one label `core.kubebb.k8s.com.cn/rollback: "true"` to componentplan, then controller will auto rollback to componentplan's revision.
> feat: componentplan support rollback

- controllers/componentplan_controller.go
> fix: componentplan install filed output nil error

- api/v1alpha1/rating_test.go
/kind feature
add rating test cases.
For #194
> feat: add rating unit test cases

- config/samples/example-test.sh
remove some debug log from example-test, like
```
Error from server (NotFound): components.core.kubebb.k8s.com.cn "repository-bitnami-sample.nginx" not found
W0825 06:47:39.384693   15354 helpers.go:692] --dry-run is deprecated and can be replaced with --dry-run=client.
jq: error (at <stdin>:1): Cannot iterate over null (null)
```
> chore: update example-test output

- codecov.yaml
> chore: update codecov to ignore zz_generated

- pkg/helm/helm.go
- pkg/helm/repo.go
- pkg/helm/repo_test.go
- pkg/repository/http_watcher.go
- pkg/repository/iwatch.go
- pkg/repository/oci_watcher.go
> feat: add https authentication on repository

- .github/workflows/example_test.yaml
- config/samples/core_v1alpha1_rating_1.yaml
- config/samples/core_v1alpha1_rating_2.yaml
- config/samples/pipeline-helm-lint.yaml
- config/samples/pipeline-rback-helm-lint.yaml
- config/samples/pipeline-rback.yaml
- config/samples/task-helm-lint.yaml
- config/samples/task-rback.yaml
- config/samples/tekton_test.sh
/kind feature
feat: add example-test for rating
Fix: https://github.com/kubebb/core/issues/293
https://github.com/0xff-dev/core/actions/runs/5973617083/job/16206305101
> feat: add example-test for rating

- .github/workflows/image_build.yml
> chore: add a new version tag to new image

- config/samples/example-test.sh
- pkg/helm/cmd.go
- pkg/helm/helm.go
> fix: Long time installation continues even after uninstallation done 

- api/v1alpha1/repository.go
- controllers/repository_controller.go
Identify official components
Fixes #229
Related to the [PR](https://github.com/kubebb/components/pull/100)
> feat: add labels to indicate official components in the repository

- api/v1alpha1/repository.go
- pkg/helm/helm.go
- pkg/repository/iwatch.go
/kind bug
fix: helm command failed to read file
Fixes #
> fix: helm command failed to read file

- api/v1alpha1/component_types.go
- api/v1alpha1/component_webhook.go
- config/crd/bases/core.kubebb.k8s.com.cn_components.yaml
- config/webhook/manifests.yaml
- main.go
/kind feature
feat: add creator in component labels
Fix: https://github.com/kubebb/core/issues/317
```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Component
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"core.kubebb.k8s.com.cn/v1alpha1","kind":"Component","metadata":{"annotations":{},"labels":{"kubebb.component.repository":"kubebb"},"name":"aaaaa","namespace":"kubebb-system","ownerReferences":[{"apiVersion":"core.kubebb.k8s.com.cn/v1alpha1","kind":"Repository","name":"kubebb","uid":"fc37dc4a-7d42-4fe0-bae4-8bbe9df1a0c4"}]},"spec":{}}
creationTimestamp: "2023-09-01T08:24:04Z"
generation: 1
labels:
core.kubebb.k8s.com.cn/component-creator: kubernetes-admin
kubebb.component.repository: kubebb
name: aaaaa
namespace: kubebb-system …
```
> feat: add creator in component labels

- .github/workflows/example_test.yaml
- config/samples/core_v1alpha1_rating_1.yaml
- config/samples/core_v1alpha1_rating_2.yaml
- config/samples/core_v1alpha1_rating_llm.yaml
- config/samples/rating_test.sh
/kind bug
Fixes #330 
To enable rating tests with AI evaluator, I created a new environment `Dev`(configured as `manuall approval required`) in our github actions and created a secret `LLM_API_KEY`.
the `rating-test` workflow utliize `Dev` environment and read `LLM_API_KEY` as the environment variables. 
When user made a pull request, this `rating-test` requires manually approval from reviewers.  See below for more details:
1.  wating for approval
2.  review pending deployments
> fix: bugs in rating test with ai evaluator

- api/v1alpha1/repository_test.go
/kind test
chore: add test cases for repository
For #194
> chore: add test cases for repository

- PROJECT
- api/v1alpha1/repository.go
- api/v1alpha1/repository_webhook.go
- api/v1alpha1/webhook_suite_test.go
- config/samples/core_v1alpha1_repository_oci_test.yaml
- config/samples/example-test.sh
- config/webhook/manifests.yaml
- main.go
> feat: change OCI URL

- controllers/repository_controller_test.go
- controllers/suite_test.go
- pkg/repository/mock/mock_chart_repo_server.go
/kind test
feat: repo test cases
For #194
> feat: repo test cases

- config/manager/manager.yaml
/kind bug
fix: core pod OOm
Fixes #
> fix: core pod OOm

- controllers/repository_controller.go
/kind bug
fix: too long to delete repository
Fixes #355
> fix: too long to delete repository

- pkg/repository/http_watcher_test.go
- pkg/repository/mock/mock_chart_repo_server.go
/kind test
feat: add test cases for http_watcher
For #194
> feat: add test cases for http_watcher

- .github/workflows/image_build.yml
> fix: Modify submitted version image

- api/v1alpha1/repository_test.go
/kind test
chore: add testcase for repository ParseRepoSecret
For #194
> chore: add testcase for repository ParseRepoSecret

- pkg/utils/path.go
- pkg/utils/path_test.go
/kind test
chore: add testcases for pkg/utils/path.go
For #194
> chore: add testcases for pkg/utils/path.go

- api/v1alpha1/component.go
- config/manager/manager.yaml
- controllers/component_controller.go
- main.go
- pkg/helm/helm_chart_workpool.go
/kind bug
feat: use workpool to reduce operator memory usage
Fixes #
> feat: use workpool to reduce operator memory usage

- cmd/core/main.go
- go.mod
- pkg/cmd/config.go
- pkg/cmd/create_core.go
/kind feature
feat: cli basic framework
For #315
> feat: cli basic framework

- Makefile
- pipeline/lowcode/README.md
- pipeline/lowcode/chart-template/Chart.yaml
- pipeline/lowcode/chart-template/templates/deployment.yaml
- pipeline/lowcode/chart-template/templates/ingress.yaml
- pipeline/lowcode/chart-template/templates/portal.yaml
- pipeline/lowcode/chart-template/templates/service.yaml
- pipeline/lowcode/chart-template/values.yaml
- pipeline/lowcode/kustomization.yaml
- pipeline/lowcode/pipeline.yaml
- pipeline/lowcode/sample/install-component.yaml
- pipeline/lowcode/sample/pre-publish.yaml
- pipeline/lowcode/sample/publish.yaml
- pipeline/lowcode/sample/schema.json
- pipeline/lowcode/task-build-chart.yaml
- pipeline/lowcode/task-build-image.yaml
- pipeline/lowcode/task-fetch-source.yaml
/kind feature
Fixes #162 
Fixes #356 
Remained issues:
- copy menu.yaml to helm charts
> feat: able to automatically build and publish lowcode components

- api/v1alpha1/subscription.go
- api/v1alpha1/subscription_webhook.go
/kind feature
For quick search
Fixes #
> feat: add component label for subscription

- config/samples/example-test.sh
- controllers/componentplan_controller.go
- pkg/helm/common.go
> fix: cpl cant uninstall when component not found

- api/v1alpha1/component_types.go
- config/crd/bases/core.kubebb.k8s.com.cn_components.yaml
- controllers/component_controller.go
- pkg/helm/helm_chart_workpool.go
- pkg/repository/http_watcher.go
/kind bug
fix: remove all associated configmaps when the component is deprecated
Fixes #
> fix: remove all associated configmaps when the component is deprecated

- config/samples/example-test.sh
- pkg/helm/cpl_helm.go
- pkg/helm/cpl_helm_release_workpool.go
> fix: some cpl will uninstall failed
