config/samples/example-test.sh, controllers/componentplan_controller.go
Update componentplan_controller.go to check if the plan is approved before installing, and update example-test.sh with a correct Grafana image.
This change ensures that the component plan is not installed until it has been approved, providing better control and minimizing unnecessary installations. Also, the example script now uses the correct Grafana image for testing purposes.
=> fix: Skip installation if component plan not approved

.github/workflows/release.yaml, .goreleaser.yaml, goreleaser.dockefile
Implemented Goreleaser configuration to automate release process ensuring that it is consistent, repeatable, and reliable. A new `.goreleaser.yaml` file is added for organizing build, Docker image creation and pushing to Dockerhub, and program versioning. Also included custom templates for structuring of release notes. New GitHub action workflow `release.yaml` has also been added, it's triggered by pushing tags and performs the release using Goreleaser. This improvement eliminates the need for manual compilation and publishing thus increasing the efficiency of the release process.
Fix #70
=> Add Goreleaser configuration and GitHub action for releases

api/v1alpha1/repository.go, controllers/componentplan_controller.go, pkg/helm/cmd.go, pkg/repository/chartmuseum.go
1. `ComponentPlan Contoller` and `ChartMuseum watcher` use same repo name (`namespace.name`)
```shell
➜  examples git:(dev) ✗ k ge
➜  examples git:(dev) ✗ helm repo list
NAME                	URL
kubebb-system.kubebb	https://kubebb.github.io/components
➜  examples git:(dev) ✗
```
2. Fix: https://github.com/kubebb/components/issues/28
=> fix: use NamespacedName as the helm repo name

tests/kind-config.yaml
To integrate with building base, port 80&443 should be exposed by default. BTW... single node with building base has been tested on Azure VM
=> fix: expose port 80&443 for ingress

api/v1alpha1/menu_types.go, config/crd/bases/core.kubebb.k8s.com.cn_menus.yaml
fix: set the maximum length of menu names to 64 characters
=> fix: set the maximum length of menu names to 64 characters

api/v1alpha1/common.go, api/v1alpha1/common_test.go
feat: versioned filter on component ignore
Fix: https://github.com/kubebb/core/issues/96
=> feat: versioned filter on component ignore

.github/workflows/example_test.yaml, config/samples/example-test.sh, controllers/componentplan_controller.go, pkg/helm/cmd.go, pkg/helm/helm.go
- add syncMap and reduce unnecessary retry reconcile request (Fix #126) prevents multiple installations（Neither cpl.status nor helm releases are real-time, and there will be edge-case errors with these two judgments, but they can be used as a judgment condition after operator restarts) (xref #85)
- simplify componentplan's patchStatus function
- helm log update, fix helm installation ns (Fix #105)
- increase the concurrency of example-test from 5 to 10
- fix the problem in example-test and add the verification of helm revision after componentplan installation.
Fix https://github.com/kubebb/core/actions/runs/5585781404/jobs/10209054157#step:6:140 and https://github.com/kubebb/core/actions/runs/5595656655/jobs/10231821540
=> fix: helm action concurrency issues

api/v1alpha1/common.go, api/v1alpha1/common_test.go, api/v1alpha1/repository_types.go, config/crd/bases/core.kubebb.k8s.com.cn_repositories.yaml
Fix #96 
Replace filter.operation with filter.enabled.
=> refactor: versioned filter on component ignore

.github/update-helm-chart-version.sh, .github/workflows/update-helm-chart-pr.yaml
Introducing a new ci tool that automatically updates the [`kubebb/core` helm chart file](https://github.com/kubebb/components/tree/main/charts/kubebb-core) in `kubebb/components` when a new version of `kubebb/core` is released, modifying 3 things: 
- the version of the image in `values.yaml` https://github.com/kubebb/components/blob/ce52f847581e23dae312b35f478ac00aed899f84/charts/kubebb-core/values.yaml#L2
- the `appversion` https://github.com/kubebb/components/blob/ce52f847581e23dae312b35f478ac00aed899f84/charts/kubebb-core/Chart.yaml#L6 (which is the same as the image version) and `version` https://github.com/kubebb/components/blob/ce52f847581e23dae312b35f478ac00aed899f84/charts/kubebb-core/Chart.yaml#L5 (patch version auto plus 1) in `Chart.yaml` 
- synchronizing the crds file …
=> ci: new github action to sync helm chart

controllers/component_controller.go
=> fix: If the resource has been deleted, stop the function in time

api/v1alpha1/common.go, config/crd/bases/core.kubebb.k8s.com.cn_componentplans.yaml, config/crd/bases/core.kubebb.k8s.com.cn_subscriptions.yaml, pkg/helm/helm.go
We have compared all the helm install/upgrade/uninstall parameters, and there are 3 scenarios:
1. It is configurable in cpl config.
2. We don't support the configuration, the reason also appears in the comment of the config field and also in the crd of the cpl.
3. We are not sure if we want to support it now, the TODO appears in the comment of the config field
=> feat: add cpl config: cleanupOnFail and keepHistory, matches to the helm install/upgrade/uninstall args

api/v1alpha1/condition.go, pkg/repository/chartmuseum.go
fix: repository events are not updated
At present, if the continuous synchronization `succeeds` or `fails`, the `Message`, `Reason`, `Type`, and `Status` fields do not change, and the `LastTransitionTime` and `LastSuccessfulTime` cannot be set normally.
=> fix: repository events are not updated

api/v1alpha1/common_test.go
/kind test
add test cases for `ComponentVersion.Equal` function.
For https://github.com/kubebb/core/issues/194
=> chore: add test cases for ComponentVersion.Equal

.github/workflows/example_test.yaml
fix issue like https://github.com/kubebb/core/actions/runs/5937625058/job/16100509925#step:6:90
```
/home/runner/work/core/core/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
test -s /home/runner/work/core/core/bin/kustomize || { curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 3.8.7 /home/runner/work/core/core/bin; }
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
make: *** [Makefile:195: /home/runner/work/core/core/bin/kustomize] Error 1
```
=> test: skip install kustomize to avoid Github rate-limiter failure

config/samples/example-test.sh, pkg/helm/helm.go, pkg/helm/helm_test.go, pkg/repository/oci_watcher.go
Fix #252 
```bash
$ helm pull oci://registry-1.docker.io/bitnamicharts/nginx --version 15.0.2
Pulled: registry-1.docker.io/bitnamicharts/nginx:15.0.2
Digest: sha256:32d95bdf27824295fcb8a9f7dd8e2b001524a9181d514076586f90565e986401
```
It is same with https://hub.docker.com/r/bitnamicharts/nginx/tags?page=1&name=15.0.2
we can use this digest for oci repo.
=> fix: oci repo has no digest

api/v1alpha1/repository.go, config/samples/example-test.sh, controllers/repository_controller.go
Fix: https://github.com/kubebb/core/issues/318
Only a way to enable `manually restart` with this new lable. Not tested yet. Not committed to work....
=> feat: add a label to trigger repository restart

api/v1alpha1/rating_types.go, api/v1alpha1/repository_types.go, config/crd/bases/core.kubebb.k8s.com.cn_ratings.yaml, config/crd/bases/core.kubebb.k8s.com.cn_repositories.yaml, config/samples/core_v1alpha1_rating_3.yaml, config/samples/core_v1alpha1_repository_kubebb_2.yaml, config/samples/rating_test.sh, controllers/rating_controller.go
=> feat:add a new filed EnableRating in repository

codecov.yaml
/kind cleanup
chore: ignore testing of webhook files
=> chore: ignore testing of webhook files

pkg/helm/common.go
/kind bug
fix: unsupported namespace setting during creation
Fixes #
```go
getter := genericclioptions.ConfigFlags{
APIServer:   &cfg.Host,
CAFile:      &cfg.CAFile,
BearerToken: &cfg.BearerToken,
Namespace:   &c.cfg.Namespace,
}
logger := logr.Logger{}
hl, err := helm.NewHelmWrapper(&getter, c.cfg.Namespace, logger)
actionClient := hl.GetDefaultInstallCfg()
_, _, err = hl.Install(ctx, logger, actionClient, &c.cfg.Args, "kubebb-core", fmt.Sprintf("%s/kubebb-core", KUBEBB_OFFICIAL_REPO))
```
Result
```
ClusterRoleBinding.rbac.authorization.k8s.io "kubebb-core" is invalid: subjects[0].namespace: Required value
```
=> fix: unsupported namespace setting during creation

api/v1alpha1/condition.go, config/samples/rating_test.sh, controllers/rating_controller.go, pkg/evaluator/evaluator.go
=> feat: tracking rating status

config/samples/example-test.sh, controllers/componentplan_controller.go, controllers/subscription_controller.go
=> fix: sub update cant update cpl when cpl has created

api/v1alpha1/repository.go, config/samples/example-test.sh, controllers/repository_controller.go
=> feat: auto detect repositoryType

controllers/componentplan_controller.go, pkg/helm/cpl_helm.go
=> fix: cpl latest should handle helm operation

controllers/subscription_controller.go
=> feat: add componentplan-release label to subscription

pkg/evaluator/evaluator.go, pkg/evaluator/prompt.go
/kind optimize
fix: optimize prompt output
Fixes #
=> fix: optimize prompt output

README.md, hack/quick-install.sh
/kind feature
feat: add a install script
Fixes #
```shell
root@ecs-4fc018ff-1ded-4c65-92dc-67dc1911226c:~/workspace/core/hack$ ./install.sh 
nodename: kubebb-core-worker, nodeip: 172.18.0.2
1. add repo as kubebb
"kubebb12" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kubebb12" chart repository
...Successfully got an update from the "kubebb123" chart repository
...Successfully got an update from the "kubebb" chart repository
Update Complete. ⎈Happy Helming!⎈
2. create namespace u4a-system, kubebb-system
namespace/u4a-system unchanged
namespace/kubebb-system unchanged
3. install kubebb-core in namesapce kubebb-system with name kubebb-core
kubebb-core-component installed …
```
=> feat: add a install script
